# PNBTR Training Thresholds Configuration
# Defines accuracy targets, metric weights, and quality standards

# Mastery threshold - composite accuracy required for success
mastery_threshold: 0.90 # 90% accuracy required

# Individual metric weights for composite scoring
# Sum should equal 1.0 for proper weighting
weights:
  SDR: 0.35 # Signal-to-Distortion Ratio (highest weight)
  DeltaFFT: 0.25 # Spectral fidelity via FFT comparison
  EnvelopeDev: 0.20 # Dynamic envelope preservation
  PhaseSkew: 0.10 # Temporal/phase alignment
  DynamicRange: 0.05 # Dynamic range retention
  FrequencyResponse: 0.05 # Frequency response retention

# Quality tier definitions
quality_tiers:
  excellent: 0.95 # 95%+ - Nearly perfect reconstruction
  very_good: 0.90 # 90-95% - Mastery threshold range
  good: 0.80 # 80-90% - Acceptable for most applications
  fair: 0.70 # 70-80% - Noticeable but still usable
  poor: 0.50 # 50-70% - Significant degradation
  very_poor: 0.0 # <50% - Unacceptable quality

# Individual metric minimum thresholds
# Any metric below these values triggers warnings
metric_minimums:
  SDR: 0.70 # Minimum signal-to-distortion ratio
  DeltaFFT: 0.60 # Minimum spectral preservation
  EnvelopeDev: 0.70 # Minimum envelope preservation
  PhaseSkew: 0.80 # Minimum phase alignment
  DynamicRange: 0.60 # Minimum dynamic range retention
  FrequencyResponse: 0.60 # Minimum frequency response

# Training behavior settings
training:
  max_attempts: 1000 # Maximum training iterations per sample
  early_stopping: true # Stop if no improvement for N iterations
  early_stopping_patience: 50 # Iterations without improvement before stopping

  # Learning rate scheduling
  learning_rate:
    initial: 0.001
    decay_factor: 0.95
    decay_patience: 20 # Iterations before decay
    minimum: 0.00001

  # Convergence criteria
  convergence:
    tolerance: 0.001 # Minimum improvement per iteration
    window: 10 # Moving average window for convergence check

# Scoring modes and their parameters
scoring_modes:
  composite:
    description: "Standard weighted average of all metrics"

  conservative:
    description: "Penalizes poor individual metrics more heavily"
    penalty_threshold: 0.70 # Below this triggers penalty
    penalty_factor: 0.20 # Up to 20% composite penalty

  optimistic:
    description: "Rewards when most metrics perform well"
    good_threshold: 0.80 # Threshold for 'good' metric
    good_fraction: 0.75 # Fraction of metrics that must be good
    bonus_factor: 0.05 # 5% bonus when criteria met

# Field deployment criteria
field_deployment:
  minimum_composite: 0.85 # Minimum score for field deployment
  minimum_consistency: 10 # Minimum successful samples needed
  confidence_threshold: 0.95 # Confidence level for deployment

# Advanced thresholds for specific signal types
signal_type_thresholds:
  voice:
    weights:
      SDR: 0.40 # Voice quality depends heavily on SDR
      DeltaFFT: 0.20
      EnvelopeDev: 0.25 # Speech dynamics important
      PhaseSkew: 0.10
      DynamicRange: 0.03
      FrequencyResponse: 0.02

  music:
    weights:
      SDR: 0.30
      DeltaFFT: 0.30 # Musical spectral content crucial
      EnvelopeDev: 0.20
      PhaseSkew: 0.08
      DynamicRange: 0.07 # Musical dynamics important
      FrequencyResponse: 0.05

  transient:
    weights:
      SDR: 0.25
      DeltaFFT: 0.20
      EnvelopeDev: 0.15
      PhaseSkew: 0.25 # Timing critical for transients
      DynamicRange: 0.10
      FrequencyResponse: 0.05

# JVID-specific thresholds (video signal processing)
jvid_thresholds:
  color_fidelity: 0.85 # Minimum color accuracy
  temporal_stability: 0.80 # Frame-to-frame consistency
  spatial_resolution: 0.90 # Spatial detail preservation

# Performance benchmarks
benchmarks:
  target_processing_time_ms: 0.8 # <1ms field processing target
  training_time_limit_hours: 24 # Maximum training time per sample
  memory_limit_gb: 16 # Memory usage limit

# Adaptive threshold management
adaptive_thresholds:
  enabled: false # Enable dynamic threshold adjustment
  adjustment_rate: 0.01 # 1% adjustment per update
  success_rate_target: 0.60 # Target 60% success rate
  adjustment_window: 100 # Samples to evaluate for adjustment

# Debugging and analysis
debug:
  save_failed_samples: true # Save samples that fail to reach threshold
  detailed_logging: true # Enable comprehensive logging
  generate_plots: false # Generate visualization plots (requires matplotlib)
  plot_format: "png" # Plot file format

# Version and metadata
version: "1.0"
created_date: "2025-01-08"
description: "PNBTR Training threshold configuration based on audio science research"
philosophy: "Anti-float, anti-dither: 24-bit precision, analog emulation over digital excuses"
